### PR TITLE
#19 unable to locate its companion shared library error on mac os sierra

### PR DESCRIPTION
**Pull request by newpcraft**
- add .DS_Store file to decorate dmg image
- add dmg file build script
- make the app open with a proper workspace path, named as `CUBRIDManager` in the Documents folder of the user home on mac osx
- need `genisoimage` to generate dmg file on linux

### CODE REVIEW

**Comment by newpcraft** [comment]
When you open dmg image after build the mac osx package, you will see the following window:



So, you can make it drag-n-drop into your own Application folder.

**Comment by newpcraft** [comment]
@seunghun-kim Would you do build test with this PR in build server?

**Comment by seunghun-kim** [comment]
@newpcraft I was build your changed about this PR. 
As a result, CM is good working without shared library error in OS X sierra.
By the way, I faced one problem when I executed dmg image. 
The below image is not same as your expected window.
screen shot 2017-03-23 at 9 43 43 am

Woud you please check this problem?
You can download that dmg image on `ftp://ftp.cubrid.org/CUBRID_Tools/CUBRID_Manager/DEV/CUBRIDManager-9.3.6.007-macosx-cocoa.dmg`
(ftp:// is not linking to anchor tag in markdown... 😢 )

**Comment by seunghun-kim** [comment]
@newpcraft The dmg image is good working! Thank you. 😄

**Pull request merged**
