### PR TITLE
ShowDashboard: add \n to message so it splits

### PR DESCRIPTION
**Pull request by paulgheorghecristian**
dash
The message is too big for this unresizable window. Adding a \n splits this message and it looks ok now.
dash2

### CODE REVIEW

**Comment by seunghun-kim** [comment]
I think your platform is Linux, right?
In OSX and Windows, that message is not split.
So, I think that message printing should be different at Linux.
How about add the OS checking logic in `ShowDashboardDialog` class?
Above class is exist in package of `com.cubrid.common.ui.common.preference`.

**Comment by newpcraft** [comment]
@paulgheorghecristian @seunghun-kim When the message is longer than width of the dialog, it can reproduce also on mac os. How about adding SWT.WRAP bit in `new Button()` as a button style on the `ShowDashboardDialog` class without the message update?

**Comment by paulgheorghecristian** [comment]
@newpcraft that works perfectly for me. thanks!

**Comment by newpcraft** [comment]
LGTM

**Pull request merged**
