### PR TITLE
RowToColumnGood: rename some strings

### PR DESCRIPTION
**Pull request by paulgheorghecristian**
Selecting a query result's element and clicking "View Details..." would actually yield column info, not row info. I've changed some labels.
row

### CODE REVIEW

**Comment by paulgheorghecristian** [comment]
I have one question regarding this task. When clicking View Details(Inspect Row with this update), the window that opens contains a widget that supposedly lets you edit the selected row. That isn't the case though, the text isn't editable. Can anyone give me some insight about this?

**Comment by seunghun-kim** [comment]
I have same question.
I think that task is not need editable widget because that's main purpose is just show inspect the selected row.

@newpcraft How about your opinion?

**Comment by newpcraft** [comment]
@paulgheorghecristian @seunghun-kim 

Do you means the following dialog?



If so, it should be `Column Detailed Information` rather than `Row`.

Basically, so that it would be strange for users showing editable form in the dialog, I'd like to make it readonly style.

However, I've an idea with this dialog to be better useful while editing a cell.

When you click the edit button like this:


you will see the editable cell in the row. And then you can commit and rollback what you changed cells in that row by using following buttons:

 
So, when the edit mode, we can use the popup dialog(detailed view) to let an user edit something on wide editor instead of cell(narrow) directly if an user wanted.



If there are readonly mode in a query result pane, the detailed view dialog also shows as readonly mode. It would be better useful when editing with long string or date time which has some format.

**Comment by newpcraft** [comment]
@paulgheorghecristian 
It may be better to be named as `Inspect column` instead of `Inspect row` due to a function for a column.



Moreover, as above image, even though it allows to click `View details...` menu, but it couldn't be work because as I remember it works only for a column(but it selected `No` index column as you see). So, when user choose a row and open the context menu, it would better to hide or disable the `View details...` menu item.

**Comment by paulgheorghecristian** [comment]
@newpcraft  I have changed the name from row to column and, also, I disable the "Inspect column..." (View details...) menu option if necessary (instead of showing an error message box).

**Comment by newpcraft** [comment]
LGTM

**Pull request merged**
