### PR TITLE
EditHostDialog: remove a message and change another

### PR DESCRIPTION
**Pull request by paulgheorghecristian**
edut
It is not desired to have 3 messages with the same string. I have removed one and changed the other ( the main title remains unchanged).

### CODE REVIEW

**Comment by seunghun-kim** [comment]
Changed message is looks good. 👍 

The other dialog boxes contains their own title. 
If we delete the title only in here, this is not balanced with other dialog boxes.
So, I think title should be print as before.

Would you please compare below two images and give your opinion to me. 😄 
- When title is not deleted.
before

- When title is deleted.
after

**Comment by paulgheorghecristian** [comment]
@seunghun-kim indeed, we leave it unbalanced if we remove the title. I think that we should remove the title from everywhere because I find the duplicated messages redundant (I'm not sure why they were put in the first place). Do you think we could do that?

For example, why should we show "edit host" or "login database" twice?

**Comment by newpcraft** [comment]
In most of cases, that title is not helping for users. Moreover, without the title view, we all know what it is. So, I'd like to remove title on all dialogs. What if we do this, we may have to adjust margin in title area like this:

**Comment by seunghun-kim** [comment]
@paulgheorghecristian 
I'm agree to remove the title in all dialogs and that will be balanced.
So, I think removing the title in all dialogs is good.

**Comment by newpcraft** [comment]
@paulgheorghecristian If so, it would be ok without resizing the top margin in the title area.

By the way, what do you think to override the `setTitle()` in the `CMTitleAreaDialog` class in order to hide a title in all dialog once?

**Comment by paulgheorghecristian** [comment]
@newpcraft I don't think we should do that, wouldn't that leave us with a lot of "setTitle" calls that don't do anything?

**Comment by newpcraft** [comment]
@paulgheorghecristian If you think that it would be better to remove all `setTitle` method calls, you can do that.

**Comment by kisoo-han** [comment]
* Close outdated PR

**Pull request closed without merging**
