### PR TITLE
cannot execute a query that it has a sqlmap syntax tags

### PR DESCRIPTION
**Pull request by newpcraft**
When the query has sqlmap tags such as `<select>`, `<update>`, `<insert>`,
`<delete>`, cubrid manager expects to parse as well as transform that
query to a normal query which allows to be executed in the query editor
through parameter binding step.

However, some query might possible to have such tags in conditions. In
this condition, when you run a query, it couldn't execute because
cubrid manager handles that query as a sqlmap rather than a normal
query. So, it is always failed.

For example, you cannot run the following query:

```
SELECT * FROM code WHERE s_name='<select></select>'
```

For this reason, we should have to provide sqlmap parsing function with
an extra action rather than a query run action. Because even if it has
a function to distinguish between a normal and a sqlmap query in the
query editor, but it is not enough with such simple logic.

In this patch, I added a new menu item in the context menu of the query
editor as `Parse this sqlmap query` which located under the `Run this
query` menu item. When you click this menu, it will parse the query as
the sqlmap and make it open the Sqlmap pane on the right side of the
query editor due to binding parameters.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMap PUBLIC "-//iBATIS.com/DTD SQL Map 2.0//EN" "http://ibatis.apache.org/dtd/sql-map-2.dtd">
<sqlMap namespace="namespace1">

<select id="t1" parameterClass="map">
SELECT * FROM code WHERE s_name=#s_name#;
</select>

</sqlMap>
```

Click the `Parse this sqlmap query` menu on selected query:

It will show this panel to bind parameters and paste normal query to the new query editor tab:

### CODE REVIEW

**Comment by newpcraft** [comment]
When the query has sqlmap tags such as <select>, <update>, <insert>,
<delete>, cubrid manager expects to parse as well as transform that
query to a normal query which allows to be executed in the query editor
through parameter binding step.

However, some query might possible to have such tags in conditions. In
this condition, when you run a query, it couldn't execute because
cubrid manager handles that query as a sqlmap rather than a normal
query. So, it is always failed.

For example, you cannot run the following query:

```
SELECT * FROM code WHERE s_name='<select></select>'
```

For this reason, we should have to provide sqlmap parsing function with
an extra action rather than a query run action. Because even if it has
a function to distinguish between a normal and a sqlmap query in the
query editor, but it is not enough with such simple logic.

In this patch, I added a new menu item in the context menu of the query
editor as `Parse this sqlmap query` which located under the `Run this
query` menu item. When you click this menu, it will parse the query as
the sqlmap and make it open the Sqlmap pane on the right side of the
query editor due to binding parameters.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMap PUBLIC "-//iBATIS.com/DTD SQL Map 2.0//EN" "http://ibatis.apache.org/dtd/sql-map-2.dtd">
<sqlMap namespace="namespace1">

<select id="t1" parameterClass="map">
SELECT * FROM code WHERE s_name=#s_name#;
</select>

</sqlMap>
```

Click the `Parse this sqlmap query` menu on selected query:



It will show this panel to bind parameters and paste normal query to the new query editor tab:

**Comment by newpcraft** [comment]
@seunghun-kim Would you please review the PR?

**Comment by newpcraft** [comment]
Updated error messages:

```
sqlmapEmptyContent=빈 SQLMap 개체로 인해 분석할 수 없습니다.
sqlmapInvalidFormat=잘못된 형식의 SQLMap 문서 입니다.
sqlmapNoMybatisFormat=문서에 ibatis 또는 mybatis 형식인지 구분을 위한 헤더가 없습니다.

sqlmapEmptyContent=There is an empty content in the sqlmap object.
sqlmapInvalidFormat=The sqlmap document has an invalid format in contents.
sqlmapNoMybatisFormat=The document should have a proper header to be detected whether ibatis or mybatis format.
```

**Comment by newpcraft** [comment]
@seunghun-kim Would you please check it again?

**Comment by seunghun-kim** [comment]
@newpcraft LGTM! 👍

**Pull request merged**
